/*
Danah Stallings
Homework 1: strings, string methods, and numerical variables
Feb 8, 2026
*/

#include <iostream>
using namespace std;

int main(){
    cout<<"\t---- Use AI to Generate the Code: Activity 1 ---- "<<endl;

    // declare variables
    double celsius;
    double fahrenheit;

    // Assign test value
    celsius = 20;

    // Convert Celsius to Fahrenheit
    fahrenheit =(celsius * 9.0/5.0) + 32;

    cout<<"Celsius: "<<celsius<<"degrees"<<endl;
    cout<<"Fahrenheit: "<<fahrenheit<<"degrees"<<endl;

    cout<<"\t---- Use AI to Generate the Code: Activity 2 ---- "<<endl;
    // Add User Input
    cout<<"Temperature Conversion Program"<<endl;
    cout<<"Enter temperature in Celsius: ";
    cin>>celsius;

    // Convert Celsius to Fahrenheit
    fahrenheit =(celsius * 9.0/5.0) + 32;

    cout<<"Converted temperature in Fahrenheit: "<<fahrenheit<<"degrees"<<endl; 

    cout<<"\t---- Use AI to Generate the Code: Activity 3 ---- "<<endl;
    // Add Conversion Choice
    double temperature;
    double convertedTemperature;
    int choice;

    cout<<"Temperature Conversion Program" <<endl;
    cout<<"------------------------------" <<endl;
    cout<<"Choose an option:" <<endl;
    cout<<"1. Celsius to Fahrenheit" <<endl;
    cout<<"Fahrenheit to Celsius" <<endl;
    cout<<"Enter your choice (1 or 2): ";

    if(choice==1)
    {
        cout<<"Fahrenheit Celsius: ";
        cin>>temperature;

        convertedTemperature =(temperature * 9/5) + 32;

        cout<<"Temperature in Fahrenheit: "<<convertedTemperature<<"degrees"<<endl;
    }
    else if(choice==2)
    {
        cout<<"Enter temperature in Fahrenheit: ";
        cin>>temperature;

        convertedTemperature =(temperature - 32) * 5/9;

        cout<<"Temperature in Celsius: "<<convertedTemperature<<"degrees"<<endl;
    }
    else
    {
        cout<<"invalid choice. Please run the program again and select 1 or 2."<<endl;
    }
    
    return 0;
}

// 1. Does the AI code use C++ concepts you're unfamiliar with? Explain.
        Yes, the AI code do use C++ concets that I'm familiar with. I recently understood why a user would use the "double".

    // 2. Are there any issues or improvements you noticed? Explain.
        I noticed that code that is generated by AI, can be extentivse.

    // 3. What test cases did you try, and why? Explain.
        I used the "if and else statements because I'm little more fimilar with these.
